name: Build Vue for etekweb.net
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Rickynunez123'
        reponame: 'portfolio'
        gitmsg: '🚀 Deploy Vue 3 to GitHub Pages'
        cname: 'rnunezcu.com'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged